version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
        - data:/var/lib/postgresql/data
    command: -p 5433 # This is to change the default port of postgres
volumes:
    data:
